# Site wide configuration

title: Kite-Mallorca.com - International Kitesurf Centre
description: Mallorcas kitesurf school number one
logo: kite-mallorca_150x118.png
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url: http://kite-mallorca.com

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner: 
  name: Kitesurf Mallorca SL
  email: team@kite-mallorca.com
  twitter: kite_mallorca
  google: Kitesurf Mallorca
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
